title: Learning how to use Github
author: Mark
email: 0x0000263A@tuta.io
description: > # this means to ignore newlines until "baseurl:"
  Should have learned how to use Git properly, years ago.

# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  meo182 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
